### ISSUE TITLE
Error on opening UE4

### ISSUE THREAD

**Issue by ghost** [Pozitrone/WakaTimeForUE4#27]
Hi I got a problem that I cant use this plugin.
my UE version is 4.27
and I got this on the opening
![Screenshot 2022-06-29 215850](https://user-images.githubusercontent.com/69420353/176499745-5b303cca-2942-41b4-977b-4cedc8853c88.png)

**Comment by TheAshenWolf** [comment]
Hello, 
please, try to rebuild the plugin using the IDE (open plugin in Visual studio, Rider, etc., whatever you are using, and run build within your project)

Alternatively, you can try removing the Intermediate and Bin folders, which may help too.

My last idea is to use the plugin as a project plugin, instead of an editor plugin (place it into the project's plugin folder, instead of the engine's one).

I hope one of these tips will help you solve the issue :) 

Have a nice day!

**Comment by ghost** [comment]
Thank you, the solution you said worked, but I encountered a problem in building with this line
[//#include "UObject/ObjectSaveContext.h"](https://github.com/TheAshenWolf/WakaTimeForUE/blob/1093fe25c5e5e406d90c522d19c522e55dd228b8/Source/WakaTimeForUE/Private/WakaTimeForUE.cpp#L15)
That I changed it with this one
`#include "UObject/Object.h"`
and build were successfully
