### ISSUE TITLE
is not working in ue 5.3.1

### ISSUE THREAD

**Issue by Rxxbertx** [Pozitrone/WakaTimeForUE4#32]
i see the logo of wakatime and i have the correct api key, but is not working

**Comment by Rxxbertx** [comment]
also, is not compile the plugin.. i need to use it like a project plugin

**Comment by TheAshenWolf** [comment]
When you copy the API code from the website, it's in the format `waka_[api_key]`. Could you please ensure, that you are only pasting in the api key, without the `waka_` prefix? 

As far as compilation when it comes to editor/project plugin, I am not sure what could be wrong there. Since I do not have UE5 installed, I am unable to check at this point.

**Comment by Rxxbertx** [comment]
hi, i use waka_[api_key] format with waka_ prefix.

**Comment by Rxxbertx** [comment]
> When you copy the API code from the website, it's in the format `waka_[api_key]`. Could you please ensure, that you are only pasting in the api key, without the `waka_` prefix?
> 
> As far as compilation when it comes to editor/project plugin, I am not sure what could be wrong there. Since I do not have UE5 installed, I am unable to check at this point.

![imagen](https://github.com/TheAshenWolf/WakaTimeForUE/assets/104899410/38911efd-8ee8-43c6-9043-7ad8024d2635)

**Comment by Rxxbertx** [comment]
![imagen](https://github.com/TheAshenWolf/WakaTimeForUE/assets/104899410/04d662b5-2d88-48d2-85d7-6cc8f09473e3)
now is working :) (without [waka_])
